version: "3.9"

services:
  pg-0:
    image: bitnami/postgresql-repmgr:14
    ports:
      - 5432
    volumes:
      - pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=default-db
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d default-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgpool:
    image: bitnami/pgpool:latest
    ports:
      - 5432:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432:0:pg-0:ALLOW_TO_FAILOVER
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=custompassword
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=adminpassword
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
    depends_on:
      pg:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: ./balance-service, ./stats
      dockerfile: ./migrate.Dockerfile
    environment:
      - POSTGRES_HOST=pgpool
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=postgres
    depends_on:
      pgpool:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmqctl status" ]
      interval: 5s
      timeout: 5s
      retries: 10

  balance-service:
    build:
      context: ./balance-service
      dockerfile: ./Dockerfile
    ports:
      - "5050:5050"
    environment:
      - POSTGRES_HOST=pgpool
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=postgres
      - LOG_LEVEL=debug
      - ADDR=5050
      - JWT_EXPIRATION=10
      - JWT_KEY=passed
      - RABBITMQ_DSN=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_QUEUE=worker
    depends_on:
      migrations:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy

  stats:
    build:
      context: ./stats
      dockerfile: ./Dockerfile
    ports:
      - "5051:5051"
    environment:
      - POSTGRES_HOST=pgpool
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=postgres
      - LOG_LEVEL=debug
      - ADDR=5050
      - JWT_EXPIRATION=10
      - JWT_KEY=passed
      - RABBITMQ_DSN=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_QUEUE=worker
    depends_on:
      migrations:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy

volumes:
  pg_data:
    driver: local