# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build balance-service
      run: go build -v ./balance-service

    - name: Test balance-service
      run: go test -v ./balance-service
      
    - name: Build stats-service
      run: go build -v ./stats

    - name: Test stats-service
      run: go test -v ./stats
      
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.3.1
